name:                memebot
version:             0.1.0.0
github:              "dreamsmasher/saiko-backend"
license:             BSD3
author:              "Norman Liu"
maintainer:          "normanwuweiliu@gmail.com"
copyright:           "Copright 2020 Norman Liu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dreamsmasher/saiko-backend#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- warp
- mtl
- transformers
- containers
- aeson
- lens
- bytestring
- text
- http-types
- contravariant
- contravariant-extras
- time
- attoparsec
- product-profunctors
- calamity
- polysemy
- req
- split
- unordered-containers
- lens-aeson
- data-default
- http-client
- http-api-data
- discord-haskell
- async
- extra

library:
  source-dirs: src
  ghc-options: -O2 -flate-specialise -fspecialise-aggressively
  default-extensions:
    - DataKinds
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - TupleSections
    - OverloadedStrings
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies

executables:
  memebot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - memebot
    default-extensions:
      - DataKinds
      - FlexibleContexts
      - GADTs
      - LambdaCase
      - TupleSections
      - OverloadedStrings
      - PolyKinds
      - RankNTypes
      - ScopedTypeVariables
      - TypeApplications
      - TypeOperators
      - TypeFamilies


tests:
  saiko-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - saiko-backend
